name: Staging Build
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: |
          yarn install
      - name: Staging Build
        run: |
          yarn build
      #     - name: Unit Tests
      #       run: |
      #         yarn test
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ s3.AWS_STAGING_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ s3.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ s3.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ s3.AWS_REGION }}
          SOURCE_DIR: "build"
